In [37]:
# Import Libraries

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
# Load the data

hosp_df = pd.read_csv(r"J:\Porfolio_Projects\Hospital_Patient_Records\hospital_patients_real_world.csv")

In [39]:
hosp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      5000 non-null   str
 1   Age            4650 non-null   float64
 2   Gender         4650 non-null   str
 3   Diagnosis      4650 non-null   str
 4   AdmissionDate  5000 non-null   str
 5   DischargeDate  5000 non-null   str
 6   HospitalID     5000 non-null   str
dtypes: float64(1), str(6)
memory usage: 273.6 KB

In [40]:
def basic_checks(df):
    print(f"Shape of data(Rows * Columns)\n{df.shape}")
    print("-"*100)
    print(f"Datatypes:\n {df.info()}")
    print("-"*100)
    print(f"Numerical stats:\n {display(df.describe(include=['int','float']).T)}")
    print("-"*100)
    print(f"Categorical stats:\n {display(df.describe(include=['str']).T)})")
    print("-"*100)
    print(f"Missing values:\n {(df.isnull().sum())/(len(df))}")
    print("-"*100)
    print(f"Duplicated Values:\n{df.duplicated().sum()}")
    print("-"*100)

In [41]:
basic_checks(hosp_df)

Shape of data(Rows * Columns)
(5000, 7)
----------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      5000 non-null   str
 1   Age            4650 non-null   float64
 2   Gender         4650 non-null   str
 3   Diagnosis      4650 non-null   str
 4   AdmissionDate  5000 non-null   str
 5   DischargeDate  5000 non-null   str
 6   HospitalID     5000 non-null   str
dtypes: float64(1), str(6)
memory usage: 273.6 KB
Datatypes:
 None
----------------------------------------------------------------------------------------------------

      count       mean        std  min   25%   50%   75%   max
Age  4650.0  47.384301  27.880535  0.0  23.0  47.0  72.0  95.0

Numerical stats:
 None
----------------------------------------------------------------------------------------------------

              count unique                      top  freq
PatientID      5000   5000               PN-2021066     1
Gender         4650      4                    Other  1223
Diagnosis      4650     28  Urinary Tract Infection   342
AdmissionDate  5000    999               2025-06-03    14
DischargeDate  5000   1002               2024-04-29    13
HospitalID     5000     90                  HOSP-25    72

Categorical stats:
 None)
----------------------------------------------------------------------------------------------------
Missing values:
 PatientID        0.00
Age              0.07
Gender           0.07
Diagnosis        0.07
AdmissionDate    0.00
DischargeDate    0.00
HospitalID       0.00
dtype: float64
----------------------------------------------------------------------------------------------------
Duplicated Values:
0
----------------------------------------------------------------------------------------------------

In [42]:
missing_cols = hosp_df[['Age','Gender','Diagnosis']]

print(missing_cols)

       Age   Gender                Diagnosis
0      7.0    Other    Myocardial Infarction
1     36.0    Other                Pneumonia
2     70.0    Other                Influenza
3     90.0  Unknown         Acute Bronchitis
4      0.0   Female          Type 2 Diabetes
...    ...      ...                      ...
4995  22.0   Female                      NaN
4996   NaN    Other    Myocardial Infarction
4997   0.0     Male  Urinary Tract Infection
4998  29.0    Other  Urinary Tract Infection
4999  93.0    Other           Cholelithiasis

[5000 rows x 3 columns]

In [52]:
num_nulls = hosp_df['Age']
cat_nulls = hosp_df[['Gender','Diagnosis']]

In [53]:
def quality_fix(df):
    df['Age'] = df['Age'].fillna(df['Age'].mean())
    df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
    df['Diagnosis'] = df['Diagnosis'].fillna('No diagnosis given')
    print(df.isnull().sum())

In [54]:
quality_fix(hosp_df)

PatientID        0
Age              0
Gender           0
Diagnosis        0
AdmissionDate    0
DischargeDate    0
HospitalID       0
dtype: int64

In [ ]:
# Preprocessing pipeline: